### ISSUE TITLE
emailtoken 로긴 시 username 30글자 제한

### ISSUE THREAD

**Issue by midnightradio** [pythonkr/pyconapac-2016#20]
로긴을 시도하면 Server Error (500) 이라고 출력되던데 다 그런 줄 알고 있다가 보아하니 저만 그런 것 같아서 살펴봤습니다. django.contrib.auth.models.User  에서 username 이 30글자로 제한되어있어서 생기는 문제 같습니다. 제 이메일 주소 길이가 33 이거든요. 어떻게 방법이 없을까요? 최소한 validation 이라도...

**Comment by lqez** [comment]
@midnightradio 기본 모델의 길이를 100자로 수정했습니다. 다시 한 번 테스트 해주시면 감사드리겠습니다.

**Comment by midnightradio** [comment]
@lqez 로긴 잘 되네요. thx
