### ISSUE TITLE
earlybird 티켓구매 결제 문제

### ISSUE THREAD

**Issue by midnightradio** [pythonkr/pyconapac-2016#21]
티켓구매 결제 시 결제한도초과 오류가 납니다.

개인카드 두 개로 시도해봤는데 둘 다 그렇습니다.

둘 다 한도초과되지 않은 카드들입니다.제

아둘러 법인카드 결제 시 개인카드와 똑같이 "비밀번호 앞 2글자" 를 물어보는데, 법인카드 비밀번호를 알고 사용하는 경우는 거의 없을 것이므로 사용성 개선이 될 수 있다면 좋겠네요.

**Comment by midnightradio** [comment]
확인 차 다시 시도해봤고 정확한 에러메시지는 다음과 같습니다.

"결제에 실패했습니다. -1 결제승인에 실패하였습니다. [2116]개인 월 한도금액 초과"

**Comment by JosephDev** [comment]
저도 같은 오류입니다.
참고로 영문페이지에서 결제했는데 오류 메세지는 한글로 리턴되었습니다.

**Comment by iiogmgo** [comment]
한도 초과 문제는 PG사의 문제로 보입니다. 해결 중에 있습니다. 감사합니다.

**Comment by midnightradio** [comment]
네, 이제 결제가 되네요. 법인카드 비밀번호를 몰라서 개인카드로 결제했는데 아마 저 같은 사람들이 많을 겁니다. 법인카드 비밀번호 알고 쓰는 사람이 거의 없을테니까요.
