### ISSUE TITLE
영문버전에서 결제시 한글이 나옵니다.

### ISSUE THREAD

**Issue by JosephDev** [pythonkr/pyconapac-2016#22]
결제 페이지에서 언어가 영어로 지정되어있음에도 한글로 내용이 출렵됩니다.

<img width="365" alt="screen shot 2016-04-14 at 8 25 16 pm" src="https://cloud.githubusercontent.com/assets/7818008/14550634/24ff7d9a-027f-11e6-963d-248d142546ea.png">
<img width="854" alt="screen shot 2016-04-14 at 8 25 31 pm" src="https://cloud.githubusercontent.com/assets/7818008/14550635/25049e92-027f-11e6-8801-aa488c5e1652.png">

**Comment by woojing** [comment]
291c5d6153470fed02f09bb964c3831436806a2c 에서 해결하였습니다.
