### ISSUE TITLE
결제방법이 bank transfer 일때도 transactionID가 있어야만 상세페이지에서 저장이 가능함.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconapac-2016#24]
결제방법이 신용카드일때는 transactionID가 있지만, bank transfer일때는 없습니다. 상세페이지에서 수정한후 저장하려고 하면 transactionID가 필수로 지정되어 있어서 저장이 안됩니다. (아무거나 넣어도 상관은 없음) 

결제 수단에 따라  required가 다르게 지정되거나, required에서 빠져야할 것 같습니다.

**Comment by woojing** [comment]
aa8c83df056446eff7336450d8c3c81651121ece 에서 수정했습니다.
