### ISSUE TITLE
프로필을 먼저 만들어주세요 오류...

### ISSUE THREAD

**Issue by statkclee** [pythonkr/pyconapac-2016#25]
Name: 이광춘
Phone: 82-
Organization: xwMOOC
Bio:
Victor (Kwangchun) Lee is the founder of XWMOOC, a digital contents startup for computational thinking and software engineering in Korea. He set up business and system architecture for Free Trade Agreement (FTA) and Origin Management at the Hyundai Motor Company, and led automotive semiconductor developement and purchasing at Hyundai Autron. Victor has master's degrees in software engineering and statistics, and contributed to the Korean translation of Software Carpentry and hosted four Software Carpentry Workshops in Korea.

상기 정보를 https://www.pycon.kr/2016apac/profile/edit 사이트에 넣었습니다.

![pycon01](https://cloud.githubusercontent.com/assets/5325425/14602816/e8cec78a-05a4-11e6-8133-2cf2821b0aba.PNG)

그러면 다음과 같은 오류가 나옵니다.
![pycon_error](https://cloud.githubusercontent.com/assets/5325425/14602815/e8ccd1dc-05a4-11e6-90e1-6e5d39bc3c75.PNG)

**Comment by lqez** [comment]
제보해주셔서 감사합니다.
해당 문제는 한글 파일 이름으로 발생한 문제이며, 수정하도록 하겠습니다.

**Comment by statkclee** [comment]
발표자 등록 성공적으로 마무리했습니다.
감사합니다 ^^;
