### ISSUE TITLE
아임 포트의 해외결제 가능성확인

### ISSUE THREAD

**Issue by woojing** [pythonkr/pyconapac-2016#3]
메뉴얼에 특별한 언급이 없어서 아임 포트에 별도로 확인 메일을 보내고 기다리는중
해외결제쪽에 특별한 문제가 없으면 페이팔구현은 제외하려고함

**Comment by woojing** [comment]
다음과 같이 답변 받았으며 아직 테스트 해보지는 않음

```
현재 아임포트의 해외카드 지원내용은, 

- VISA / Master / JCB카드 결제가 가능 (AMEX 카드 결제 불가)
- 결제 시 USD승인이 불가하고 KRW로만 승인 가능(FX비용이 구매자에게 추가 청구되고 판매자에게는 발생하지 않습니다)
```

**Comment by iz4blue** [comment]
해외 카드 결제에 대해서 새로운 업체를 찾으신다면 : https://www.eximbay.com 도 있습니다.

**Comment by woojing** [comment]
현재 구현인 onetime 결제의 경우 외국인 결제가 이루어지지 않음.
아임포트 개발팀에 문의 넣을 예정.

**Comment by woojing** [comment]
아임포트 통해서 해외결제 구현 완료 하였습니다.
