### ISSUE TITLE
스프린트/튜토리얼 페이지의 참석자 기본 아이콘이 없으면 다른 이미지를 보여주도록 수정이 필요합니다.

### ISSUE THREAD

**Issue by corazzon** [pythonkr/pyconapac-2016#35]
스프린트/튜토리얼 상세 페이지에 참석자명과 프로필사진이 없을 때 다른 이미지와 대체 문구를 보여주도록 수정이 필요합니다.
https://www.pycon.kr/2016apac/program/tutorial/3

**Comment by lqez** [comment]
Fixed. Thanks!
