### ISSUE TITLE
GA 계정 새로 파고 적용 및 전달

### ISSUE THREAD

**Issue by lqez** [pythonkr/pyconapac-2016#7]

**Comment by lqez** [comment]
UA-75675713-1

**Comment by woojing** [comment]
@lqez 이거 어떻게 접근하나요? woojing@pycon.kr 계정으로 GA 들어가도 연결된게 없는것 같아서요 :(

**Comment by lqez** [comment]
GA admin 에서 추가했습니다. 메일링으로 하려고 했더니 잘 안되네요 :(
